
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
public class checkout extends javax.swing.JFrame {

    Connection con = null;
    Statement st = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public checkout() {
        initComponents();
        SimpleDateFormat obj = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        // Çıkış tarihi alanına bugünün tarihini ekler
        txtoutdate.setText(obj.format(date));

        try {
            // Veritabanına bağlantı oluşturulur
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/otel", "root", "");
        } catch (ClassNotFoundException ex) {
            // Sürücü sınıfı bulunamazsa log kaydı oluşturulur
            Logger.getLogger(manageRoom.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            // Veritabanı hatası oluşursa log kaydı oluşturulur
            Logger.getLogger(manageRoom.class.getName()).log(Level.SEVERE, null, ex);
        }
        // Tabloya kayıtları gösterme işlemi yapılır
        showDateIntoTable();
    }

    public void showDateIntoTable() {
        try {
            // Müşteri tablosundan "status" alanı "NULL" olan kayıtları seçer
            pst = con.prepareStatement("select * from customer where status=?");
            pst.setString(1, "NULL");
            rs = pst.executeQuery();

            // Sonuç kümesinin meta verilerini alır
            ResultSetMetaData ob = rs.getMetaData();
            int n = ob.getColumnCount(); // Sütun sayısını alır

            DefaultTableModel df = (DefaultTableModel) jTable1.getModel(); // Tablo modelini alır
            df.setRowCount(0); // Tablonun satır sayısını sıfırlar

            while (rs.next()) {
                Vector v = new Vector(); // Yeni bir vektör oluşturur
                // Sütunlardaki verileri vektöre ekler
                for (int i = 1; i <= n; i++) {
                    v.add(rs.getString("name"));
                    v.add(rs.getString("mobile"));
                    v.add(rs.getString("id"));
                    v.add(rs.getString("roomnumber"));
                    v.add(rs.getString("bed"));
                    v.add(rs.getString("roomtype"));
                    v.add(rs.getString("joindate"));
                    v.add(rs.getString("billid"));
                    v.add(rs.getString("nationality"));
                }
                df.addRow(v); // Vektörü tabloya ekler
            }

        } catch (SQLException ex) {
            // Veritabanı hatası oluşursa log kaydı oluşturulur
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtroomnumber = new javax.swing.JTextField();
        btnSearchRoom = new javax.swing.JButton();
        txtcustomername = new javax.swing.JTextField();
        txttcno = new javax.swing.JTextField();
        txtmobile = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtindate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtoutdate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        txtdays = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Customer Check Out.png"))); // NOI18N
        jLabel1.setText("Musteri Checkout Yap");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 101, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Musteri Adi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Telefon Numarasi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("TC Numarasi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 150, -1));
        getContentPane().add(txtroomnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 93, 106, 32));

        btnSearchRoom.setText("Oda Ara");
        btnSearchRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchRoomActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 98, -1, -1));

        txtcustomername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtcustomername, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 178, 150, 39));

        txttcno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txttcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttcnoActionPerformed(evt);
            }
        });
        getContentPane().add(txttcno, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 150, 39));

        txtmobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 150, 39));

        txtprice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        getContentPane().add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 283, 150, 39));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Gun Basina Fiyat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, -1));

        txtindate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtindate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 150, 39));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Checkin Tarihi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 150, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Checkout Tarihi(Bugun)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 170, -1));

        txtoutdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtoutdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoutdateActionPerformed(evt);
            }
        });
        getContentPane().add(txtoutdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 150, 39));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Musteri Adi", "Telefon No", "TC No", "Oda No", "Yatak Tipi", "Oda Tipi", "Checkin Tarih", "Fatura No", "Uyruk"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 449, 836, 364));

        btnClear.setBackground(new java.awt.Color(151, 53, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Temizle");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 159, 48));

        btnCheckout.setBackground(new java.awt.Color(151, 53, 0));
        btnCheckout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("Checkout Yap");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 165, 48));

        txtdays.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaysActionPerformed(evt);
            }
        });
        getContentPane().add(txtdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 150, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Kaldigi Gun Sayisi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Total Fatura");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 150, -1));

        txtamount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamountActionPerformed(evt);
            }
        });
        getContentPane().add(txtamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 150, 39));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txttcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttcnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttcnoActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        try {
            // Müşteri kaydını günceller: checkout yapıldı, çıkış tarihi, kaldığı gün sayısı ve ödenen miktar bilgileri eklenir
            pst = con.prepareStatement("update customer set status=?, outdate=?, day=?, amount=? where roomnumber=? and joindate=?");
            pst.setString(1, "Checkout Yapildi"); // Müşteri durumunu günceller
            pst.setString(2, txtoutdate.getText()); // Çıkış tarihini günceller
            pst.setString(3, txtdays.getText()); // Kaldığı gün sayısını günceller
            pst.setString(4, txtamount.getText()); // Ödenen miktarı günceller
            pst.setString(5, txtroomnumber.getText()); // Oda numarasını belirler
            pst.setString(6, txtindate.getText()); // Giriş tarihini belirler
            pst.executeUpdate(); // Güncelleme sorgusunu çalıştırır

            // Oda kaydını günceller: oda durumu "Rezerve Yok" olarak güncellenir
            pst = con.prepareCall("update room set status=? where roomnumber=? ");
            pst.setString(1, "Rezerve Yok"); // Oda durumunu günceller
            pst.setString(2, txtroomnumber.getText()); // Oda numarasını belirler
            pst.executeUpdate(); // Güncelleme sorgusunu çalıştırır

            JOptionPane.showMessageDialog(this, "Checkout Başarılı."); // Başarılı çıkış mesajı gösterir
            showDateIntoTable(); // Tabloyu günceller

            // Alanları temizler
            txtcustomername.setText("");
            txtmobile.setText("");
            txttcno.setText("");
            txtprice.setText("");
            txtdays.setText("");
            txtindate.setText("");
            txtoutdate.setText("");
            txtamount.setText("");

        } catch (SQLException ex) {
            // Veritabanı hatası oluşursa log kaydı oluşturur
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtoutdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoutdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoutdateActionPerformed

    private void btnSearchRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchRoomActionPerformed
        try {
            // Veritabanından oda numarasına göre müşteri bilgilerini arar
            pst = con.prepareStatement("select * from customer where roomnumber=? and status=?");
            pst.setString(1, txtroomnumber.getText()); // Arama kriteri olarak oda numarasını belirler
            pst.setString(2, "NULL"); // Müşterinin çıkış yapmadığı durumu belirler
            rs = pst.executeQuery(); // Sorguyu çalıştırır
            if (rs.next()) {
                // Eğer müşteri bulunursa, müşteri bilgilerini alır
                txtcustomername.setText(rs.getString("name")); // Müşteri adını gösterir
                txtmobile.setText(rs.getString("mobile")); // Müşteri telefon numarasını gösterir
                txttcno.setText(rs.getString("id")); // Müşteri kimlik numarasını gösterir
                txtprice.setText(rs.getString("price")); // Oda ücretini gösterir
                txtindate.setText(rs.getString("joindate")); // Giriş tarihini gösterir

                // Müşterinin çıkış tarihi ve giriş tarihleri arasındaki gün farkını hesaplıyoruz.
                String s1, s2;
                s1 = txtoutdate.getText(); // Çıkış tarihini alır(Bugün olarak)
                s2 = rs.getString("joindate"); // Giriş tarihini alır
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");

                Date d1 = format.parse(s1); // Çıkış tarihini tarih nesnesine dönüştürür
                Date d2 = format.parse(s2); // Giriş tarihini tarih nesnesine dönüştürür
                long tarihFarki = d1.getTime() - d2.getTime(); // Gün farkını hesaplar
                // Gün farkını tarih cinsinden integer gün cinsine dönüştürür
                int days = (int) tarihFarki / (24 * 60 * 60 * 1000); 
                if (days == 0) {
                    // Eğer gün farkı 0 ise, minimum bir gün olarak kabul eder
                    // Yani aynı gün içinde giriş-çıkış yapan olursa gün=1 olur.
                    days = 1; 
                }
                txtdays.setText(String.valueOf(days)); // Kalış süresini gösterir
                // Toplam ödenecek miktarı hesaplar (amount=günlük ücret(price) * toplam kalış(days) )
                double price = Double.parseDouble(rs.getString("price")) * days;
                txtamount.setText(String.valueOf(price)); // Toplam ödenecek miktarı gösterir
            }

        } catch (SQLException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSearchRoomActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //Temizleye bastığında girilen form alanları temizler.
        txtcustomername.setText("");
        txtmobile.setText("");
        txttcno.setText("");
        txtprice.setText("");
        txtdays.setText("");
        txtindate.setText("");
        txtoutdate.setText("");
        txtamount.setText("");

    }//GEN-LAST:event_btnClearActionPerformed

    private void txtdaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaysActionPerformed

    private void txtamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearchRoom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcustomername;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtindate;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtoutdate;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtroomnumber;
    private javax.swing.JTextField txttcno;
    // End of variables declaration//GEN-END:variables
}
